name: Basic Test
on: [push, pull_request]

jobs:
  riscv64_job:
    # The host should always be linux
    runs-on: ubuntu-18.04
    name: Build on archlinux riscv64
    steps:
      - uses: actions/checkout@v3
      - uses: light4/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: riscv64
          distro: archlinux

          # Not required, but speeds up builds
          githubToken: ${{ github.token }}

          run: |
            uname -a
            echo ::set-output name=uname::$(uname -a)

      - name: Get the output
        run: |
          echo "The uname output was ${{ steps.runcmd.outputs.uname }}"
